export const ORGANIZATIONS_DETAILS_REQUEST = 'ORGANIZATIONS_DETAILS_REQUEST';
export const ORGANIZATIONS_DETAILS_SUCCESS = 'ORGANIZATIONS_DETAILS_SUCCESS';
export const ORGANIZATIONS_DETAILS_FAIL = 'ORGANIZATIONS_DETAILS_FAIL';
